### ISSUE TITLE
/Profile need validation for username.

### ISSUE THREAD

**Issue by Fofofosho** [doppl3r/teamfling#5]
For description and roles, is it allowed to be empty?

**Comment by Fofofosho** [comment]
need jquery or form validation to prevent POST from occurring.

**Comment by doppl3r** [comment]
The only required field is the username, and it must not be empty. Maybe we can generate a default name like "HACKER6". A simple html5 'required' value will be more than enough.

`<input name="{user.name}" type="text" required>`

What are your thoughts?

**Comment by Fofofosho** [comment]
if we get free form validation using the `required` statement then try that. We could also generate one if they don't enter one in though, easy to do.

**Comment by Fofofosho** [comment]
Im closing this since `required` works. If we want to make it special using the flash functionality we have for register, then we can revisit.
